# Jekyll Defaults
title: CapriconCoder
description: A small and simple site out Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog

url: ""
github: http://github.com/capriconcoder
highlighter: rouge
markdown: kramdown

permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: "#"
  url: /
- text: About
  url: /about/
# - text: Archives
#   url: /archives/
# - text: Tags
#   url: /tags/

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1